name: First Workflow

on:
    push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        - name: Build Text File
          run: echo "this is the first workflow" >> first_workflow.txt

        - name: upload text file
          uses: actions/upload-artifact@v4
          with:
            name: first-workflow
            path: first_workflow.txt


    test_job:
        needs: build_job
        runs-on: ubuntu-latest
        steps:
            - name: download text file
              uses: actions/download-artifact@v4
              with:
                name: first-workflow

            - name: run text file
              run: |
                ls -ltra
                cat first_workflow.txt


    deploy_job:
        needs: test_job
        runs-on: ubuntu-latest
        steps:
            - name: download text file
              uses: actions/download-artifact@v4
              with:
                name: first-workflow

            - name: run text file
              run: cat first_workflow.txt


